### ISSUE TITLE
"Generate All" note overlap

### ISSUE THREAD

**Issue by Type-kun** [Lightforger/Note-Assist#6]
Try to generate all notes at post http://danbooru.donmai.us/posts/2042048?pool_id=10077 - lower half of picture becomes one large note box, with some more generated notes inside. I think overlap prevention was coded at one point?

**Comment by Lightforger** [comment]
This is quite a bad case of connecting multiple text bubbles :(
Delete the extra notes inside the overlap is easy (though a little costly in run-time) but i really should prevent the bottom text from connecting to the bottom-left text bubble.

I allowed bubbles to connect to other bubbles diagonally so it wouldn't miss hand-written punctation marks, I'll need to turn the sensitivity down for this.

**Comment by Lightforger** [comment]
I fixed the logic that allowed bubbles to merge diagonally which made the giant note.
It still merges 2 notes instead of 4, though if you ctrl-click the large note after using generate-all it snaps to the middle text.

Deleting all the smaller notes isn't always a good idea, it can either:
- Generate a large note over background with several correct text-notes in it.
- Generate a large note over multiple texts with several small non-text notes in it.

Unfortunately i have no idea how to distinguish those 2 cases, so closing it for now.
